export default function cases(bot, m) {
	if (m.command) console.log('Upsert Messages Log : ', m);

	try {
		switch (m.command) {
			case 'hello_bot':
				m.replay({
					text: '💬 Hi there! This reply was generated by Bot.\n\n_*111CodeLabs*_',
				});
				break;

			default:
				break;
		}
	} catch (error) {
		console.log(error);
	}
}
