export default function cases(bot, m) {
	// if (m.command)
	console.log('Upsert Messages Log : ', m);

	try {
		switch (m.command) {
			case 'x':
				// m.replay({ text: `TEST : ${m.chatId}` });
				m.replay({
					buttons: [
						{
							buttonId: '.menu',
							buttonText: {
								displayText: 'ALL MENU',
							},
							type: 1,
						},
					],
					headerType: 2,
					viewOnce: true,
				});
				break;
			case 'hello_bot':
				m.replay({
					text: '💬 Hi there! This reply was generated by Bot.\n\n_*111CodeLabs*_',
				});
				break;
			case 'list_bot':
				m.replay({
					message: {
						listMessage: {
							title: '🤖 Bot Menu',
							description: 'Please choose one of the following options:',
							buttonText: 'Open Menu',
							sections: [
								{
									title: 'Main Menu',
									rows: [
										{
											title: '📰 Info',
											rowId: 'menu_info',
											description: 'Get bot information',
										},
										{
											title: '📋 Help',
											rowId: 'menu_help',
											description: 'Show help commands',
										},
									],
								},
								{
									title: 'More',
									rows: [
										{
											title: '👤 Profile',
											rowId: 'menu_profile',
											description: 'View your profile',
										},
									],
								},
							],
						},
					},
				});

				break;
			case 'button_bot':
				m.replay({
					// text: '🤖 Choose an option:',
					buttonReply: {
						id: 'btn_info',
						displayText: '📰 Info',
						index: 1,
					},
					type: 'template',
					footer: 'Bot Footer',
					// buttons: [
					// 	{
					// 		buttonId: 'btn_info',
					// 		buttonText: {
					// 			displayText: '📰 Info',
					// 		},
					// 		type: 1,
					// 	},
					// 	{
					// 		index: 'btn_help',
					// 		buttonText: {
					// 			displayText: '📋 Help',
					// 		},
					// 		type: 1,
					// 	},
					// ],
					headerType: 1,
				});
				break;
			case 'location_bot':
				m.replay({
					location: {
						degreesLatitude: -5.305443175394928,
						degreesLongitude: 119.43502012689997,
						name: 'Masjid Nurul Jannah Majannang',
					},
				});
			default:
				break;
		}
	} catch (error) {
		console.log(error);
	}
}

// {
// 	quoted: {
// 		key: {
// 			id: m.id,
// 			fromMe: false,
// 			remoteJid: m.chatId,
// 			participant: '0@s.whatsapp.net',
// 		},
// 		message: {
// 			conversation: `${m.text}`,
// 		},
// 	},
// }
// m.replay({
//     title: global.name,
//     text: 'Message With Button',
//     // footer: 'Bot Footer',
//     buttons: [
//         {
//             name: 'single_select',
//             buttonParamsJson: JSON.stringify({
//                 title: 'Option List',
//                 sections: [
//                     {
//                         title: 'Pilih Menu Yang tersedia',
//                         highlight_label: 'Menu Favorit',
//                         rows: [
//                             {
//                                 header: 'pilihan',
//                                 title: 'Menu 1',
//                                 description: 'Description',
//                                 id: 'menu1',
//                             },
//                         ],
//                     },
//                 ],
//             }),
//             // buttonId: 'btn_info',
//             // buttonText: { displayText: '📰 Info' },
//             // type: 1,
//         },
//         // {
//         // 	buttonId: 'btn_help',
//         // 	buttonText: { displayText: '📋 Help' },
//         // 	type: 1,
//         // },
//     ],
//     headerType: 1,
// });
